Fix login
cuenca-mx/ivoy-python pull request #45
Opened 2022-01-04 17:14 UTC by agarrido19

This PR will fix ivoy authentication using a fallback url on the `get_tokens` method

- closes #43 
- related https://github.com/cuenca-mx/gaita/issues/470

2022-01-04 22:37 UTC, alexviquez requested changes

2022-01-04 22:37 UTC, alexviquez commented on ivoy/client.py
> +        fallback_url: Optional[bool] = None,
porque no haces inyectable el base_url con el default actual, y solamente lo cambias para login

2022-01-04 22:38 UTC, agarrido19 commented on ivoy/client.py
> +        fallback_url: Optional[bool] = None,
Porque lo tengo que inyectar desde la creación del cliente, sería cambiarlo desde gaita entonces

2022-01-04 22:59 UTC, alexviquez commented on ivoy/client.py
> +        fallback_url: Optional[bool] = None,
porque no lo inyectas solo en el `get_token`

2022-01-05 23:38 UTC, agarrido19 commented
Not needed anymore

2022-01-05 23:38 UTC, closed without merging